config/routes.rb
Rails.application.routes.draw do
  root :to => 'intro#index'

  get 'intro/index'
  post 'list/index'
  get 'list/search'

  resources :homes

end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  before_action :set_home, only: [:show, :edit, :update, :destroy]

  # GET /homes
  # GET /homes.json
  def index
    @homes = Home.all
    @homes.each { |home|
      puts home.writeDate
    }
    @isEmpty = false
    if @homes.count == 0
      @isEmpty = true
    end

  end

  # GET /homes/1
  # GET /homes/1.json
  def show
    @date = Time.zone.today
  end

  # GET /homes/new
  def new
    @home = Home.new
  end

  # GET /homes/1/edit
  def edit
  end

  # POST /homes
  # POST /homes.json
  def create
    @home = Home.new(home_params)

    respond_to do |format|
      if @home.save
        format.html { redirect_to @home, notice: 'Home was successfully created.' }
        format.json { render :show, status: :created, location: @home }
      else
        format.html { render :new }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homes/1
  # PATCH/PUT /homes/1.json
  def update
    respond_to do |format|
      if @home.update(home_params)
        format.html { redirect_to @home, notice: 'Home was successfully updated.' }
        format.json { render :show, status: :ok, location: @home }
      else
        format.html { render :edit }
        format.json { render json: @home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homes/1
  # DELETE /homes/1.json
  def destroy
    @home.destroy
    respond_to do |format|
      format.html { redirect_to homes_url, notice: 'Home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home
      @home = Home.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_params
      params.require(:home).permit(:content, :tag, :tagColor, :writeDate)
    end
end

app/controllers/intro_controller.rb
class IntroController < ApplicationController
  def index
  end
end

app/controllers/list_controller.rb
class ListController < ApplicationController
  def index
    year = params[:year]
    month = params[:month]
    day = params[:day]
    @startTime = DateTime.strptime("#{month}-#{day}-#{year} 00:00:00.000","%m-%d-%Y %H:%M:%S").to_time
    @endTime = DateTime.strptime("#{month}-#{day}-#{year} 23:59:59.999","%m-%d-%Y %H:%M:%S").to_time

    @targetDate = @startTime
    @homes = Home.where(writeDate: @startTime...@endTime)

    @isEmpty = false
    if @homes.count == 0
      @isEmpty = true
    end

  end
  def search
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/intro_helper.rb
module IntroHelper
end

app/helpers/list_helper.rb
module ListHelper
end

app/views/homes/_form.html.erb
<%= form_for(@home) do |f| %>
  <% if @home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@home.errors.count, "error") %> prohibited this home from being saved:</h2>

      <ul>
      <% @home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :content, :placeholder => "Write Down Here :D", :id => "write-content" %>
  </div>
  <div class="field">
    <% if @home.tag == "" || @home.tag == nil %>
      <button type="button" class="btn btn-new popover-event" data-toggle="popover" data-placement="right">
        Set Tag🚦
      </button>
    <% else %>
      <button type="button" class="btn btn-dark btn-new popover-event" data-toggle="popover" data-placement="right">
        <%= @home.tag %>
      </button>
    <% end %>
    <%= f.hidden_field :tag %>
    <%= f.hidden_field :tagColor %>
  </div>
  <div class="field hidden">
    <%= f.label :writeDate %><br>
    <%= f.datetime_select :writeDate %>
  </div>
  <div class="actions">
    <%= f.submit "Let's Go 😎", :class => "btn btn-new-submit" %>
  </div>
<% end %>

app/views/homes/edit.html.erb
<script type="text/javascript">
var content = [];
$(document).ready(function () {
  var template = '<div class="popover" role="tooltip"><div class="popover-arrow"></div><h3 class="popover-title"></h3><div class="popover-content"></div></div>';

  var tagColor = ['#EE220C', '#4051FF', '#2CC22F', '#FFBE03'];
  var tagName = ['School', 'Game', 'Sleep', 'Workout'];

  for (var i = 0; i < tagColor.length; i++) {
      var temp = '<button type="button" onclick="styleTagButton('+ i +')" class="btn btn-dark popover-event"><div class="circle tag-label" style="background-color:' +
                    tagColor[i]+ '"'+ '></div><span>' +
                    tagName[i] + '</span></button>';
      content.push(temp);
  }

  var popoverContent = content.join('');

  $('.popover-event').popover({
        content: popoverContent,
        template: template,
        placement: "right",
        html: true
    });
});

function styleTagButton(tag) {
  $(".btn-new").html(content[tag]);
  $(".btn-new").css({"background-color": "rgb(67,67,67)", "padding": "0"});

  var tagName = $(".btn-new > .btn-dark > span").html();
  setTagData(tagName);
}

function setTagData(tagName) {
  $("#home_tag").val(tagName);
}
</script>

<%= link_to homes_path, :style => "position: absolute; z-index: 9999" do %>
  <img src="/img/arrowWhite.png" alt="뒤로" style="width: 30px; margin: 20px 0px 0px 20px;opacity:  0.8;">
<% end %>
<header id="top" class="header">
    <div class="text-vertical-center">
        <h2 id="new-title">Hey, What Are You Doing? :D</h2>

        <%= render 'form' %>

    </div>
</header>

<%= link_to 'Show', @home %>

app/views/homes/index.html.erb
<header id="top" class="header">
    <div class="text-vertical-center">
      <h2 id="new-title">You Write So Far</h2>
      <% if !@isEmpty %>
      <% @homes.each do |home| %>
        <div class="card" style="width: 30rem;">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              <div class="circle tag-label" style="background-color:<%= home.tagColor %>"></div>
              🖋 <%= home.content %> <span style="float:right;margin-top: 1.5px;"><%= home.writeDate.strftime("%H:%M") %></span>
            </li>
          </ul>
        </div>
      <% end %>
      <% else %>
      <div class="card" style="width: 30rem; margin-bottom: 30px">
            You Didn't write anything :(
      </div>
      <% end %>

      <%= link_to 'Write Something 😎', new_home_path, :class => "btn btn-home btn-lg" %>
    </div>
</header>

app/views/homes/new.html.erb
<script type="text/javascript">
var content = [];
var tagColor = ['#EE220C', '#4051FF', '#2CC22F', '#FFBE03', 'rgb(187, 39, 212)'];
var tagName = ['School', 'Game', 'Sleep', 'Workout', 'Eat'];

$(document).ready(function () {
  var template = '<div class="popover" role="tooltip"><div class="popover-arrow"></div><h3 class="popover-title"></h3><div class="popover-content"></div></div>';

  for (var i = 0; i < tagColor.length; i++) {
      var temp = '<button type="button" onclick="styleTagButton('+ i +')" class="btn btn-dark popover-event"><div class="circle tag-label" style="background-color:' +
                    tagColor[i]+ '"'+ '></div><span>' +
                    tagName[i] + '</span></button>';
      content.push(temp);
  }

  var popoverContent = content.join('');

  $('.popover-event').popover({
        content: popoverContent,
        template: template,
        placement: "right",
        html: true
    });
});

function styleTagButton(tag) {
  $(".btn-new").html(content[tag]);
  $(".btn-new").css({"background-color": "rgb(67,67,67)", "padding": "0"});

  var tagName = $(".btn-new > .btn-dark > span").html();
  var color = tagColor[tag];
  setTagData(tagName, color);
}

function setTagData(tagName, color) {
  $("#home_tag").val(tagName);
  $("#home_tagColor").val(color);
}
</script>

<%= link_to homes_path, :style => "position: absolute; z-index: 9999" do %>
  <img src="/img/arrowWhite.png" alt="뒤로" style="width: 30px; margin: 20px 0px 0px 20px;opacity:  0.8;">
<% end %>
<header id="top" class="header">
    <div class="text-vertical-center">
        <h2 id="new-title">Hey, What Are You Doing? :D</h2>

        <%= render 'form' %>

    </div>
</header>

app/views/homes/show.html.erb
<header id="top" class="header">
    <div class="text-vertical-center">
      <h2 id="new-title">Your Write :D</h2>

<table>

</table>
<div class="circle"></div>
      <div class="card" style="width: 30rem;">
        <ul class="list-group list-group-flush">
          <li class="list-group-item">
            <div class="circle tag-label" style="background-color:<%= @home.tagColor %>"></div>
            🖋 <%= @home.content %> <span style="float:right;margin-top: 1.5px;"><%= @home.writeDate.strftime("%H:%M") %></span>
          </li>
        </ul>
      </div>
<!--

      <h4>🖋 <%= @home.content %></h4>
      <p><%= @home.writeDate.strftime("%Y/%-m/%-d %H:%M %Z") %></p>

      <button type="button" class="btn btn-dark">
        <div class="circle tag-label" style="background-color:<%= @home.tagColor %>"></div>
        <span><%= @home.tag %></span>
      </button> -->

      <form action="/list/index" method="POST">
        <input type="hidden" name="year" value="<%= @date.strftime("%Y") %>" class="date">
        <input type="hidden" name="month" value="<%= @date.strftime("%m") %>" class="date">
        <input type="hidden" name="day" value="<%= @date.strftime("%d") %>" class="date">

        <button type="submit" class="btn btn-new-submit" style="font-size:12px" name="button">See what you :D:D Today</button>
      </form>

    </div>
</header>

<%= link_to 'Edit', edit_home_path(@home) %> |
<%= link_to 'Back', homes_path %>

app/views/intro/index.html.erb
<script type="text/javascript">
  var element = document.getElementById("home-link");

</script>

<!-- Header -->
<header id="top" class="header">
    <div class="text-vertical-center">
      <img src="/img/logoWhite.png" id="logo" alt="로고" style="margin-bottom: 30px">
        <br>
        <%= link_to 'Write Down What you :D:D Today 😎', new_home_path, :class => "btn btn-home btn-lg" %>
    </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>:D:D List</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Custom CSS -->
  <link href="/css/theme.css" rel="stylesheet">

</head>
<body>

<%= yield %>

</body>
</html>

app/views/list/index.html.erb
<header id="top" class="header">
    <div class="text-vertical-center">
      <h2 id="new-title">See What You :D:D <%= @targetDate.strftime("%Y-%m-%d")  %></h2>
      <% if !@isEmpty %>
      <% @homes.each do |home| %>
        <div class="card" style="width: 30rem;">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              <div class="circle tag-label" style="background-color:<%= home.tagColor %>"></div>
              🖋 <%= home.content %> <span style="float:right;margin-top: 1.5px;"><%= home.writeDate.strftime("%H:%M") %></span>
            </li>
          </ul>
        </div>
      <% end %>
      <% else %>
      <div class="card" style="width: 30rem; margin-bottom: 30px">
            You Didn't write anything :(
      </div>
      <% end %>
      <a href="/list/search">See Another Day</a>
      <br>
      <br>
      Or
      <br>
      <br>
      <%= link_to 'Write Something 😎', new_home_path, :class => "btn btn-home btn-lg" %>
    </div>
</header>

<div class="row">
  <div class="col-lg-4 col-lg-offset-2">
      <div class="panel panel-default" style="border-color: #262626;">
          <div class="panel-heading" style="color:#ffffff; background-color: #262626; border: none;">
              Today's Write in %
          </div>
          <!-- /.panel-heading -->
          <div class="panel-body">
              <div class="flot-chart">
                  <div class="flot-chart-content" id="flot-pie-chart" style="height: 400px"></div>
              </div>
          </div>
          <!-- /.panel-body -->
      </div>
      <!-- /.panel -->
  </div>
  <div class="col-lg-4">
      <div class="panel panel-default" style="border-color: #262626;">
          <div class="panel-heading" style="color:#ffffff; background-color: #262626; border: none;">
              How Many You Write
          </div>
          <!-- /.panel-heading -->
          <div class="panel-body">
              <div class="flot-chart">
                  <div class="flot-chart-content" id="flot-bar-chart" style="height: 400px"></div>
              </div>
          </div>
          <!-- /.panel-body -->
      </div>
      <!-- /.panel -->
  </div>
</div>

<% @homes.all.group_by(&:tag).each do |home, tags| %>
    <% count = 0 %>
    <% tags.each do |tag| %>
      <% count += 1 %>
    <% end %>
<% end %>


<script src="/js/flot/excanvas.min.js"></script>
<script src="/js/flot/jquery.flot.js"></script>
<script src="/js/flot/jquery.flot.pie.js"></script>
<script src="/js/flot/jquery.flot.resize.js"></script>
<script src="/js/flot/jquery.flot.time.js"></script>

<script type="text/javascript">
$(document).ready(function() {
//Flot Pie Chart
  $(function() {

      var data = [{
          label: "School",
          data: 1
      }, {
          label: "Eat",
          data: 3
      }, {
          label: "Workout",
          data: 9
      }, {
          label: "Game",
          data: 20
      }];

      var plotObj = $.plot($("#flot-pie-chart"), data, {
          series: {
              pie: {
                  show: true
              }
          },
          grid: {
              hoverable: true
          },
          tooltip: true,
          tooltipOpts: {
              content: "%p.0%, %s", // show percentages, rounding to 2 decimal places
              shifts: {
                  x: 20,
                  y: 0
              },
              defaultTheme: false
          }
      });

  });



  $(function() {

      var barOptions = {
          series: {
              bars: {
                  show: true,
                  barWidth: 43200000
              }
          },
          xaxis: {
              mode: "time",
              timeformat: "%m/%d",
              minTickSize: [1, "day"]
          },
          grid: {
              hoverable: true
          },
          legend: {
              show: false
          },
          tooltip: true,
          tooltipOpts: {
              content: "x: %x, y: %y"
          }
      };
      var barData = {
          label: "bar",
          data: [
              [1354521600000, 1000],
              [1355040000000, 2000],
              [1355223600000, 3000],
              [1355306400000, 4000],
              [1355487300000, 5000],
              [1355571900000, 6000]
          ]
      };
      $.plot($("#flot-bar-chart"), [barData], barOptions);

  });

});

</script>

app/views/list/search.html.erb
<header id="top" class="header">
    <div class="text-vertical-center">
      <h2 id="new-title">Search Date :D</h2>

      <form action="/list/index" method="POST">
      <div class="container">
        <div class="row">
          <div class="col-xs-4">
            <h4>Year</h4>
            <div class="circle circleDate">
              <input type="text" name="year" value="" placeholder="2017" class="date">
            </div>

          </div>
          <div class="col-xs-4">
            <h4>Month</h4>
            <div class="circle circleDate">
              <input type="text" name="month" value="" placeholder="12" class="date">
            </div>
          </div>
          <div class="col-xs-4">
            <h4>Day</h4>
            <div class="circle circleDate">
              <input type="text" name="day" value="" placeholder="21" class="date">
            </div>
          </div>
        </div>

        <br>
        <br>
        <div class="row">
          <div class="col-xs-12">
            <div class="actions">
              <button type="submit" class="btn btn-new-submit" name="button">Let's See 😀</button>
            </div>
          </div>
        </div>
      </div>
    </form>
      </div>

    </div>
</header>